version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: justarone
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - /home/justarone/hdd/data:/var/lib/postgresql/data

